on:
  push:

jobs:
  delete-and-create:
    runs-on: ubuntu-latest

    steps:
      - uses: jcansdale/gpr@v0.1.257
        with:
          command: delete
          path: ${{ github.repository }}
          args: --force

      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com

      - run: npm init --scope ${{ github.repository_owner }} -y

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
